// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';
import {desktop} from '../models';

export function Accept(arg1:number,arg2:boolean):Promise<client.Job>;

export function Drop(arg1:number,arg2:boolean):Promise<client.Job>;

export function FollowLog(arg1:number):Promise<void>;

export function Job(arg1:number):Promise<client.JobDetails>;

export function Jobs(arg1:boolean):Promise<Array<client.Job>>;

export function Overview():Promise<client.Overview>;

export function Projects():Promise<Array<client.Project>>;

export function Shutdown():Promise<void>;

export function Start():Promise<desktop.StartResult>;

export function Status():Promise<desktop.Status>;

export function StopLog(arg1:number):Promise<void>;
