// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Accept(arg1, arg2) {
  return window['go']['desktop']['App']['Accept'](arg1, arg2);
}

export function AccountInstructions(arg1) {
  return window['go']['desktop']['App']['AccountInstructions'](arg1);
}

export function Accounts() {
  return window['go']['desktop']['App']['Accounts']();
}

export function AnswerCommand(arg1, arg2) {
  return window['go']['desktop']['App']['AnswerCommand'](arg1, arg2);
}

export function Conversation(arg1) {
  return window['go']['desktop']['App']['Conversation'](arg1);
}

export function Conversations() {
  return window['go']['desktop']['App']['Conversations']();
}

export function DriverModels() {
  return window['go']['desktop']['App']['DriverModels']();
}

export function Drop(arg1, arg2) {
  return window['go']['desktop']['App']['Drop'](arg1, arg2);
}

export function FollowLog(arg1) {
  return window['go']['desktop']['App']['FollowLog'](arg1);
}

export function Job(arg1) {
  return window['go']['desktop']['App']['Job'](arg1);
}

export function Jobs(arg1) {
  return window['go']['desktop']['App']['Jobs'](arg1);
}

export function Models() {
  return window['go']['desktop']['App']['Models']();
}

export function Overview() {
  return window['go']['desktop']['App']['Overview']();
}

export function Pause() {
  return window['go']['desktop']['App']['Pause']();
}

export function Projects() {
  return window['go']['desktop']['App']['Projects']();
}

export function Resume() {
  return window['go']['desktop']['App']['Resume']();
}

export function SaveAccountInstructions(arg1, arg2) {
  return window['go']['desktop']['App']['SaveAccountInstructions'](arg1, arg2);
}

export function Send(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['Send'](arg1, arg2, arg3);
}

export function SendTo(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['SendTo'](arg1, arg2, arg3, arg4);
}

export function Shutdown() {
  return window['go']['desktop']['App']['Shutdown']();
}

export function Skills(arg1) {
  return window['go']['desktop']['App']['Skills'](arg1);
}

export function Start() {
  return window['go']['desktop']['App']['Start']();
}

export function Status() {
  return window['go']['desktop']['App']['Status']();
}

export function StopLog(arg1) {
  return window['go']['desktop']['App']['StopLog'](arg1);
}

export function UpdateSkills(arg1, arg2) {
  return window['go']['desktop']['App']['UpdateSkills'](arg1, arg2);
}
