#!/bin/bash
#
# Points the coding-owl formula in the Homebrew tap at a published release. The
# release workflow runs this once the GitHub release exists. The formula is
# rendered from scratch every time, so the first run creates
# Formula/coding-owl.rb and every later run rewrites it - there is no bespoke
# first release.
#
#   VERSION=0.1.0 SHA256=<checksum of the archive> ./scripts/bump-formula.sh
#
# Environment:
#   VERSION     released version, with or without the leading v (required)
#   SHA256      sha256 of the darwin/arm64 archive (required)
#   TAP_DIR     existing checkout of the tap - cloned over ssh when unset
#   TAP_REPO    owner/name of the tap (default: vojtechmares/homebrew-tap)
#   TAP_BRANCH  branch to commit on (default: master)
#   REPO        owner/name of this project (default: vojtechmares/coding-owl)
#   ASSET_URL   the URL checked before anything is written (default: the
#               release asset itself)
#   DRY_RUN     1 to render and show the diff without checking the asset,
#               committing or pushing
#
set -euo pipefail

REPO="${REPO:-vojtechmares/coding-owl}"
TAP_REPO="${TAP_REPO:-vojtechmares/homebrew-tap}"
TAP_BRANCH="${TAP_BRANCH:-master}"
TAP_DIR="${TAP_DIR:-}"
DRY_RUN="${DRY_RUN:-0}"
VERSION="${VERSION:-}"
SHA256="${SHA256:-}"

die() {
	printf 'error: %s\n' "$*" >&2
	exit 1
}

VERSION="${VERSION#v}"
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]] ||
	die "VERSION must be a version like 0.1.0, got '${VERSION:-<empty>}'"
[[ "$SHA256" =~ ^[0-9a-f]{64}$ ]] ||
	die "SHA256 must be a 64 character hex digest, got '${SHA256:-<empty>}'"
# REPO is rendered into the formula, so it is checked like everything else that
# is: owner/name, and nothing that could be read as Ruby.
[[ "$REPO" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] ||
	die "REPO must be owner/name, got '$REPO'"
# A branch is passed to git as an argument of its own, where a leading dash
# would be read as an option rather than as a name.
[[ "$TAP_BRANCH" =~ ^[A-Za-z0-9][A-Za-z0-9._/-]*$ ]] ||
	die "TAP_BRANCH must be a branch name, got '$TAP_BRANCH'"

ARCHIVE="coding-owl_v${VERSION}_darwin_arm64.tar.gz"
URL="https://github.com/$REPO/releases/download/v$VERSION/$ARCHIVE"
ASSET_URL="${ASSET_URL:-$URL}"

# A formula pointing at a 404 is worse than no formula, so make sure the asset
# is really there before writing anything. A dry run renders without asking
# anybody, so it works with no network and no release.
if [[ "$DRY_RUN" != "1" ]]; then
	echo "==> Checking $ASSET_URL"
	curl -fsIL -o /dev/null "$ASSET_URL" ||
		die "$ARCHIVE cannot be downloaded from $ASSET_URL - is the release published?"
fi

if [[ -n "$TAP_DIR" ]]; then
	[[ -d "$TAP_DIR/.git" ]] || die "TAP_DIR is not a git checkout: $TAP_DIR"
else
	TAP_DIR="$(mktemp -d)"
	trap 'rm -rf "$TAP_DIR"' EXIT
	echo "==> Cloning $TAP_REPO"
	git clone --quiet --depth 1 --branch "$TAP_BRANCH" \
		"git@github.com:$TAP_REPO.git" "$TAP_DIR"
fi

FORMULA="$TAP_DIR/Formula/coding-owl.rb"
mkdir -p "$(dirname "$FORMULA")"

# Unquoted heredoc: $VERSION and friends expand, while Ruby's #{bin} and
# #{version} do not look like shell expansions (heredocs skip brace expansion)
# and pass through untouched.
echo "==> Rendering Formula/coding-owl.rb"
cat >"$FORMULA" <<RUBY
# typed: false
# frozen_string_literal: true

# This file is generated by the coding-owl release workflow. DO NOT EDIT.
class CodingOwl < Formula
  desc "Runs coding agents on your machine while it is otherwise idle"
  homepage "https://github.com/$REPO"
  url "$URL"
  version "$VERSION"
  sha256 "$SHA256"

  livecheck do
    url :stable
    strategy :github_latest
  end

  # darwin/arm64 is the only platform the MVP releases for (ADR-0010).
  depends_on arch: :arm64
  depends_on :macos

  def install
    bin.install "owl"
  end

  # The daemon runs in the foreground under a supervisor and never daemonizes
  # itself (ADR-0002), so brew services is what keeps it running.
  service do
    run [opt_bin/"owl", "daemon", "run"]
    keep_alive true
    log_path var/"log/coding-owl.log"
    error_log_path var/"log/coding-owl.log"
    environment_variables PATH: std_service_path_env
  end

  def caveats
    <<~EOS
      Start the daemon and keep it running across logins:

        brew services start coding-owl

      It logs to #{var}/log/coding-owl.log. Check on it with:

        owl daemon status
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/owl --version")
  end
end
RUBY

cd "$TAP_DIR"
git add Formula/coding-owl.rb

CHANGED=1
if git diff --cached --quiet; then
	CHANGED=0
	echo "==> Formula/coding-owl.rb already points at $VERSION"
else
	git --no-pager diff --cached
fi

if [[ "$DRY_RUN" == "1" ]]; then
	echo "==> Dry run, stopping here"
	exit 0
fi

if ((CHANGED)); then
	# CI runners have no git identity; locally the global one is already set.
	if ! git config user.email >/dev/null 2>&1; then
		git config user.name "github-actions[bot]"
		git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
	fi
	echo "==> Committing"
	git commit --quiet --signoff -m "chore(coding-owl): bump formula to $VERSION"
fi

# What the tap serves is what its branch on the remote says, not what this
# checkout says: a run that failed at the push has to be repeatable, and one
# with nothing to commit must not report success while the remote is still on
# the version before.
git fetch --quiet origin "$TAP_BRANCH" 2>/dev/null || true
if [[ "$(git rev-parse HEAD)" == "$(git rev-parse --verify --quiet FETCH_HEAD || echo none)" ]]; then
	echo "==> $TAP_REPO already serves coding-owl $VERSION"
	exit 0
fi

echo "==> Pushing to $TAP_BRANCH"
git push --quiet origin "HEAD:refs/heads/$TAP_BRANCH"

echo "==> $TAP_REPO now serves coding-owl $VERSION"
