#!/bin/bash
#
# Points the coding-owl-desktop cask in the Homebrew tap at a published release.
# The release workflow runs this once the GitHub release exists. The cask is
# rendered from scratch every time, so the first run creates
# Casks/coding-owl-desktop.rb and every later run rewrites it - there is no
# bespoke first release.
#
#   VERSION=0.1.0 SHA256=<checksum of the zip> ./scripts/bump-cask.sh
#
# Environment:
#   VERSION     released version, with or without the leading v (required)
#   SHA256      sha256 of the darwin/arm64 zip (required)
#   TAP_DIR     existing checkout of the tap - cloned over ssh when unset
#   TAP_REPO    owner/name of the tap (default: vojtechmares/homebrew-tap)
#   TAP_BRANCH  branch to commit on (default: master)
#   REPO        owner/name of this project (default: vojtechmares/coding-owl)
#   ASSET_URL   the URL checked before anything is written (default: the
#               release asset itself)
#   DRY_RUN     1 to render and show the diff without checking the asset,
#               committing or pushing
#
set -euo pipefail

REPO="${REPO:-vojtechmares/coding-owl}"
TAP_REPO="${TAP_REPO:-vojtechmares/homebrew-tap}"
TAP_BRANCH="${TAP_BRANCH:-master}"
TAP_DIR="${TAP_DIR:-}"
DRY_RUN="${DRY_RUN:-0}"
VERSION="${VERSION:-}"
SHA256="${SHA256:-}"

die() {
	printf 'error: %s\n' "$*" >&2
	exit 1
}

VERSION="${VERSION#v}"
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]] ||
	die "VERSION must be a version like 0.1.0, got '${VERSION:-<empty>}'"
[[ "$SHA256" =~ ^[0-9a-f]{64}$ ]] ||
	die "SHA256 must be a 64 character hex digest, got '${SHA256:-<empty>}'"
# REPO is rendered into the cask, so it is checked like everything else that is:
# owner/name, and nothing that could be read as Ruby.
[[ "$REPO" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] ||
	die "REPO must be owner/name, got '$REPO'"
# A branch is passed to git as an argument of its own, where a leading dash
# would be read as an option rather than as a name.
[[ "$TAP_BRANCH" =~ ^[A-Za-z0-9][A-Za-z0-9._/-]*$ ]] ||
	die "TAP_BRANCH must be a branch name, got '$TAP_BRANCH'"

ZIP="CodingOwl-${VERSION}-arm64.zip"
URL="https://github.com/$REPO/releases/download/v$VERSION/$ZIP"
ASSET_URL="${ASSET_URL:-$URL}"

# A cask pointing at a 404 is worse than no cask, so make sure the asset is
# really there before writing anything. A dry run renders without asking
# anybody, so it works with no network and no release.
if [[ "$DRY_RUN" != "1" ]]; then
	echo "==> Checking $ASSET_URL"
	curl -fsIL -o /dev/null "$ASSET_URL" ||
		die "$ZIP cannot be downloaded from $ASSET_URL - is the release published?"
fi

if [[ -n "$TAP_DIR" ]]; then
	[[ -d "$TAP_DIR/.git" ]] || die "TAP_DIR is not a git checkout: $TAP_DIR"
else
	TAP_DIR="$(mktemp -d)"
	trap 'rm -rf "$TAP_DIR"' EXIT
	echo "==> Cloning $TAP_REPO"
	git clone --quiet --depth 1 --branch "$TAP_BRANCH" \
		"git@github.com:$TAP_REPO.git" "$TAP_DIR"
fi

CASK="$TAP_DIR/Casks/coding-owl-desktop.rb"
mkdir -p "$(dirname "$CASK")"

# Unquoted heredoc: $VERSION and friends expand, while Ruby's #{version} and
# Homebrew's {{appdir}} do not look like shell expansions (heredocs skip brace
# expansion) and pass through untouched.
echo "==> Rendering Casks/coding-owl-desktop.rb"
cat >"$CASK" <<RUBY
# typed: strict
# frozen_string_literal: true

# This file is generated by the coding-owl release workflow. DO NOT EDIT.
cask "coding-owl-desktop" do
  version "$VERSION"
  sha256 "$SHA256"

  url "https://github.com/$REPO/releases/download/v#{version}/CodingOwl-#{version}-arm64.zip"
  name "Coding Owl"
  desc "Runs coding agents on your machine while it is otherwise idle"
  homepage "https://github.com/$REPO"

  livecheck do
    url :url
    strategy :github_latest
  end

  # In the order brew style wants them, which is not the order they read in.
  depends_on arch: :arm64
  # The app is a view over the daemon the formula ships, so the two are one
  # installation and there is exactly one daemon per machine (ADR-0010).
  depends_on formula: "coding-owl"
  depends_on macos: :ventura

  app "Coding Owl.app"

  # Homebrew 6 removed "brew install --cask --no-quarantine", so the cask has to
  # clear the flag itself. Coding Owl is ad-hoc signed but not notarised, and
  # Gatekeeper will not launch a quarantined bundle it cannot verify. Failing
  # here would abort the install after the app is already in place, and a
  # Gatekeeper prompt is the better of those two outcomes.
  postflight_steps do
    run "/usr/bin/xattr",
        args:         ["-d", "-r", "com.apple.quarantine", "{{appdir}}/Coding Owl.app"],
        must_succeed: false
  end

  uninstall quit: "dev.codingowl.desktop"

  # The app keeps nothing of its own: the daemon holds the database, the
  # credentials and the configuration, and "brew uninstall coding-owl" is what
  # takes those away.
  zap trash: [
    "~/Library/Caches/dev.codingowl.desktop",
    "~/Library/Preferences/dev.codingowl.desktop.plist",
    "~/Library/Saved Application State/dev.codingowl.desktop.savedState",
    "~/Library/WebKit/dev.codingowl.desktop",
  ]

  caveats <<~EOS
    Coding Owl is ad-hoc signed but not notarised. This cask clears the
    com.apple.quarantine flag on Coding Owl.app after installing it, which is
    what lets it launch without Gatekeeper refusing to verify it.

    The app is a view: the daemon does the work, and it comes from the
    coding-owl formula this cask depends on. Start it with

      brew services start coding-owl

    Everything Owl holds - its database, its configuration and its credentials -
    belongs to the daemon, so "brew uninstall --zap --cask coding-owl-desktop"
    removes the app and leaves those alone.
  EOS
end
RUBY

cd "$TAP_DIR"
git add Casks/coding-owl-desktop.rb

CHANGED=1
if git diff --cached --quiet; then
	CHANGED=0
	echo "==> Casks/coding-owl-desktop.rb already points at $VERSION"
else
	git --no-pager diff --cached
fi

if [[ "$DRY_RUN" == "1" ]]; then
	echo "==> Dry run, stopping here"
	exit 0
fi

if ((CHANGED)); then
	# CI runners have no git identity; locally the global one is already set.
	if ! git config user.email >/dev/null 2>&1; then
		git config user.name "github-actions[bot]"
		git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
	fi
	echo "==> Committing"
	git commit --quiet --signoff -m "chore(coding-owl-desktop): bump cask to $VERSION"
fi

# What the tap serves is what its branch on the remote says, not what this
# checkout says: a run that failed at the push has to be repeatable, and one
# with nothing to commit must not report success while the remote is still on
# the version before.
REMOTE_HEAD="none"
if git fetch --quiet origin "$TAP_BRANCH" 2>/dev/null; then
	REMOTE_HEAD="$(git rev-parse --verify --quiet FETCH_HEAD || echo none)"
fi
if [[ "$(git rev-parse HEAD)" == "$REMOTE_HEAD" ]]; then
	echo "==> $TAP_REPO already serves coding-owl-desktop $VERSION"
	exit 0
fi

echo "==> Pushing to $TAP_BRANCH"
git push --quiet origin "HEAD:refs/heads/$TAP_BRANCH"

echo "==> $TAP_REPO now serves coding-owl-desktop $VERSION"
